### ISSUE TITLE
Incompatibility with mongoose 3.6.x

### ISSUE THREAD

**Issue by lbeschastny** [mongoosejs/mongoose-number#2]
Mongoose number is incompatible with the latest `mongoose`.

The following code throws an error on `increment`:

``` coffee-script
mongoose = require 'mongoose'
require("mongoose-number") mongoose
mongoose.connect "mongodb://localhost:27017/test"

Some = mongoose.model 'Some', new mongoose.Schema
  counter: type: 'MongooseNumber', default: 0

# throws an error:
(new Some).counter.increment()
```

Here is my stacktrace:

```
TypeError: Cannot call method 'modify' of undefined
    at Number.MongooseNumber.$inc (/home/leonid/Documents/intervox/avocado/avocado/node_modules/mongoose-number/lib/type.js:43:31)
    at Object.<anonymous> (/home/leonid/Documents/intervox/avocado/avocado/test-mnumber.coffee:17:22)
    at Object.<anonymous> (/home/leonid/Documents/intervox/avocado/avocado/test-mnumber.coffee:19:4)
    at Module._compile (module.js:449:26)
    at Object.exports.run (/home/leonid/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:124:25)
    at compileScript (/home/leonid/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:166:29)
    at fs.stat.notSources.(anonymous function) (/home/leonid/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:141:18)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
```

On `Mongoose 3.5.4` everything works fine.

**Comment by aheckmann** [comment]
fixed in 0.1.0
